# -*- coding: utf-8 -*-
"""AudioBook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DBdGp9u_XosZ6l_ybLulpVRtW7MF-lJ
"""

!pip install PyPDF2

import PyPDF2

"""**Reading the pdf**"""

book = open('Data Structures and Algorithm Analysis.pdf','rb')
pdfReader = PyPDF2.PdfFileReader(book)
pages = pdfReader.numPages

"""**Extracting the text**"""

text = ""
for num in range(pages):
  page = pdfReader.getPage(num)
  text += page.extractText()

"""**Using Python text to speech module**"""

!pip install pyttsx3
!apt install libespeak1

import pyttsx3

speaker = pyttsx3.init()
speaker.say(text)
speaker.runAndWait()

"""**Using Google text to speech module**"""

!pip install  gtts
!pip install Ipython

from gtts import gTTS #Import Google Text to Speech
from IPython.display import Audio #Import Audio method from IPython's Display Class

tts = gTTS(text)
tts.save('1.wav') #save the string converted to speech as a .wav file
sound_file = '1.wav'
Audio(sound_file, autoplay=True) 

#Autoplay = True will play the sound automatically
#If you would not like to play the sound automatically, simply pass Autoplay = False.

"""**gTTS for other languages**"""

TamilText="வணக்கம்.அறம் செய விரும்பு, ஆறுவது சினம், இயல்வது கரவேல், ஈவது விலக்கேல், உடையது விளம்பேல். நன்றி!"
tts = gTTS(text=TamilText,lang='ta') #ta-Tamil Language
tts.save('1.mp3')
sound_file = '1.mp3'
Audio(sound_file, autoplay=True)